import type { Locale, LocationPack } from "./types";

export const HINT_QUESTIONS: Record<Locale, string[]> = {
  nb: [
    "Er dette et sted man vanligvis blir lenge?",
    "Ma man ofte betale for a komme inn her?",
    "Er dette stedet mest innendors eller utendors?",
    "Er det vanlig at mange mennesker er her samtidig?",
    "Trenger man spesialutstyr pa dette stedet?",
    "Er dette et sted man ofte besoker pa ferie?",
    "Kan man jobbe pa dette stedet?",
    "Er det vanlig med hoy lyd her?",
  ],
  en: [
    "Is this a place where people usually stay for a while?",
    "Do people usually pay to enter this place?",
    "Is this place mostly indoors or outdoors?",
    "Is it common for this place to be crowded?",
    "Do you need special equipment at this place?",
    "Is this place often visited while traveling?",
    "Can people work at this place?",
    "Is this place usually loud?",
  ],
};

export const PACKS: LocationPack[] = [
  {
    id: "classic",
    name: { nb: "Klassisk", en: "Classic" },
    locations: [
      { name: "Airplane" },
      { name: "Bank" },
      { name: "Beach" },
      { name: "Casino" },
      { name: "Cathedral" },
      { name: "Hospital" },
      { name: "Hotel" },
      { name: "Police Station" },
      { name: "Restaurant" },
      { name: "School" },
      { name: "Space Station" },
      { name: "Supermarket" },
    ],
  },
  {
    id: "city-life",
    name: { nb: "Byliv", en: "City Life" },
    locations: [
      { name: "Subway Station" },
      { name: "Shopping Mall" },
      { name: "Gym" },
      { name: "Cinema" },
      { name: "Library" },
      { name: "Bus Terminal" },
      { name: "Coffee Shop" },
      { name: "Parking Garage" },
      { name: "Office Building" },
      { name: "Food Court" },
    ],
  },
  {
    id: "travel",
    name: { nb: "Reise", en: "Travel" },
    locations: [
      { name: "Cruise Ship" },
      { name: "Mountain Cabin" },
      { name: "Safari Camp" },
      { name: "Ski Resort" },
      { name: "Airport Lounge" },
      { name: "Train Platform" },
      { name: "Border Checkpoint" },
      { name: "Camping Site" },
      { name: "Desert Oasis" },
      { name: "Tour Bus" },
    ],
  },
  {
    id: "nature",
    name: { nb: "Natur", en: "Nature" },
    locations: [
      { name: "Forest Trail" },
      { name: "Waterfall" },
      { name: "Cave" },
      { name: "National Park" },
      { name: "Lighthouse" },
      { name: "Fishing Pier" },
      { name: "Glacier Camp" },
      { name: "River Delta" },
      { name: "Volcano Base" },
      { name: "Rainforest Station" },
    ],
  },
  {
    id: "events",
    name: { nb: "Arrangementer", en: "Events" },
    locations: [
      { name: "Music Festival" },
      { name: "Football Stadium" },
      { name: "Convention Center" },
      { name: "Wedding Venue" },
      { name: "Art Exhibition" },
      { name: "Science Fair" },
      { name: "Film Set" },
      { name: "E-sports Arena" },
      { name: "Street Market" },
      { name: "Parade Route" },
    ],
  },
];
