import type { LocationCard, LocationPack } from "./types";

function loc(nb: string, en: string): LocationCard {
  return { name: { nb, en } };
}

const CLASSIC_LOCATIONS: LocationCard[] = [
  loc("Fly", "Airplane"),
  loc("Bank", "Bank"),
  loc("Strand", "Beach"),
  loc("Kino", "Cinema"),
  loc("Sykehus", "Hospital"),
  loc("Hotell", "Hotel"),
  loc("Politistasjon", "Police Station"),
  loc("Restaurant", "Restaurant"),
  loc("Skole", "School"),
  loc("Supermarked", "Supermarket"),
  loc("Kontor", "Office"),
  loc("Bibliotek", "Library"),
  loc("Kjøpesenter", "Shopping Mall"),
  loc("Togstasjon", "Train Station"),
  loc("Stadion", "Stadium"),
  loc("Dyrehage", "Zoo"),
  loc("Apotek", "Pharmacy"),
  loc("Bensinstasjon", "Gas Station"),
  loc("Frisør", "Hair Salon"),
  loc("Tannlege", "Dentist"),
  loc("Legevakt", "Emergency Room"),
  loc("Museum", "Museum"),
  loc("Teater", "Theater"),
  loc("Svømmehall", "Swimming Pool"),
  loc("Treningssenter", "Gym"),
  loc("Bakeri", "Bakery"),
  loc("Kafé", "Café"),
  loc("Park", "Park"),
  loc("Kirkegård", "Cemetery"),
  loc("Brannstasjon", "Fire Station"),
  loc("Postkontor", "Post Office"),
  loc("Vaskehall", "Car Wash"),
  loc("Lekeplass", "Playground"),
  loc("Flyplass", "Airport"),
  loc("Havn", "Harbor"),
  loc("Universitet", "University"),
  loc("Barnehage", "Kindergarten"),
  loc("Garasje", "Garage"),
  loc("Solstudio", "Tanning Salon"),
  loc("Tattovør", "Tattoo Parlor"),
  loc("Bruktbutikk", "Thrift Store"),
];

const NORWAY_LOCATIONS: LocationCard[] = [
  loc("Fjellhytte", "Mountain Cabin"),
  loc("Skisenter", "Ski Resort"),
  loc("Fjordferge", "Fjord Ferry"),
  loc("Fiskebrygge", "Fishing Pier"),
  loc("Stavkirke", "Stave Church"),
  loc("Tursti", "Mountain Trail"),
  loc("Seter", "Mountain Farm"),
  loc("Hurtigruteterminal", "Coastal Express Terminal"),
  loc("Rorbuhavn", "Fishermen's Cabin Harbor"),
  loc("Nasjonalpark-senter", "National Park Center"),
  loc("Utsiktspunkt", "Scenic Viewpoint"),
  loc("Isfiskeplass", "Ice Fishing Spot"),
  loc("Lakseelv", "Salmon River"),
  loc("Bunadsbutikk", "Bunad Shop"),
  loc("Vaffelstue", "Waffle Cabin"),
  loc("Nordlys-utkikkspunkt", "Northern Lights Viewpoint"),
  loc("Vikingmuseum", "Viking Museum"),
  loc("Bryggen", "Bryggen Wharf"),
  loc("Holmenkollen", "Holmenkollen"),
  loc("Trollstigen", "Troll Road"),
  loc("Preikestolen", "Pulpit Rock"),
  loc("Jostedalsbreen", "Jostedal Glacier"),
  loc("Geiranger", "Geiranger"),
  loc("Lofoten-fiskevær", "Lofoten Fishing Village"),
  loc("Hardangervidda", "Hardangervidda Plateau"),
  loc("Nidarosdomen", "Nidaros Cathedral"),
  loc("Akershus festning", "Akershus Fortress"),
  loc("Vigelandsparken", "Vigeland Park"),
  loc("Frognerparken", "Frogner Park"),
  loc("Bygdøy", "Bygdøy Peninsula"),
  loc("Flåmsbana", "Flåm Railway"),
  loc("Kystledhytte", "Coastal Trail Cabin"),
  loc("Sjømatrestaurant", "Seafood Restaurant"),
  loc("Brunost-utsalg", "Brown Cheese Shop"),
  loc("Røykelaks-fabrikk", "Smoked Salmon Factory"),
  loc("Friluftsbad", "Outdoor Swimming"),
  loc("Reinsdyrfarm", "Reindeer Farm"),
  loc("Nordkapp", "North Cape"),
  loc("Svalbard-ekspedisjon", "Svalbard Expedition"),
  loc("Polarmuseum", "Polar Museum"),
];

const AFTERSKI_LOCATIONS: LocationCard[] = [
  loc("Dr. Holms-bar", "Dr. Holms Bar"),
  loc("Havsdalen", "Havsdalen"),
  loc("Vestlia", "Vestlia"),
  loc("Kikutstua", "Kikut Cabin"),
  loc("Heiskøen", "Ski Lift Queue"),
  loc("Skibussen", "Ski Bus"),
  loc("Solterrassen", "Sun Terrace"),
  loc("Peisestua", "Fireplace Lounge"),
  loc("Varmestua", "Warming Cabin"),
  loc("Afterski-scene", "Après-Ski Stage"),
  loc("Vaffelhytta", "Waffle Cabin"),
  loc("Hyttefest", "Cabin Party"),
  loc("Slalåmbakken", "Downhill Slope"),
  loc("Skikaféen", "Ski Cafe"),
  loc("Skileie", "Ski Rental"),
  loc("Langrennsløypa", "Cross-Country Trail"),
  loc("Høyfjellshotellet", "Mountain Hotel"),
  loc("Gondolbanen", "Gondola"),
  loc("Skiheisen", "Ski Lift"),
  loc("Snøkanon", "Snow Cannon Area"),
  loc("Barneområdet", "Kids Ski Area"),
  loc("Skiskolen", "Ski School"),
  loc("Smøreboden", "Wax Hut"),
  loc("Skiservice", "Ski Service"),
  loc("Turguide-stasjon", "Tour Guide Station"),
  loc("Funpark", "Terrain Park"),
  loc("Offpiste-område", "Off-Piste Area"),
  loc("Topptur-start", "Peak Tour Start"),
  loc("Isbaren", "Ice Bar"),
  loc("Jacuzzien", "Outdoor Jacuzzi"),
  loc("Badstuen", "Sauna"),
  loc("Hotellets lobby", "Hotel Lobby"),
  loc("Pizzarestaurant", "Pizza Restaurant"),
  loc("Vinsmaking", "Wine Tasting"),
  loc("Snøskuter-tur", "Snowmobile Tour"),
  loc("Akebakken", "Sledding Hill"),
  loc("Hytteutleie", "Cabin Rental Office"),
  loc("Skisportbutikk", "Ski Shop"),
  loc("Spa-avdeling", "Spa Area"),
  loc("Pulkløype", "Sledge Trail"),
];

const EASTER_LOCATIONS: LocationCard[] = [
  loc("Påskefjellet", "Easter Mountains"),
  loc("Skistua", "Ski Cabin"),
  loc("Påskebrunsj", "Easter Brunch"),
  loc("Kiosken", "Convenience Store"),
  loc("Solkroken", "Sunny Spot"),
  loc("Eggjakten", "Egg Hunt"),
  loc("Påskelunsjbord", "Easter Lunch Table"),
  loc("Sjokoladebutikk", "Chocolate Shop"),
  loc("Påskebonfire", "Easter Bonfire"),
  loc("Kyllingstalden", "Chick Barn"),
  loc("Løypenettet", "Trail Network"),
  loc("Smeltende snø", "Melting Snow Slope"),
  loc("Familiemiddag", "Family Dinner"),
  loc("Hytteverandaen", "Cabin Porch"),
  loc("Peiskosen", "Fireplace Nook"),
  loc("Spillkvelden", "Game Night"),
  loc("Påskelam-besøk", "Easter Lamb Visit"),
  loc("Påskegudstjeneste", "Easter Service"),
  loc("Malestasjon", "Egg Painting Station"),
  loc("Heklegruppen", "Knitting Circle"),
  loc("Kvikklunsj-pausen", "KvikkLunsj Break"),
  loc("Appelsin-stasjonen", "Orange Station"),
  loc("Solstol-området", "Sun Chair Area"),
  loc("Hyttebiblioteket", "Cabin Library"),
  loc("Krimlesekroken", "Crime Novel Corner"),
  loc("Puslespillbordet", "Puzzle Table"),
  loc("Skitrening", "Ski Practice"),
  loc("Grillplassen", "Grill Area"),
  loc("Pannekakefrokosten", "Pancake Breakfast"),
  loc("Påskekonsert", "Easter Concert"),
  loc("Fjelltoppen", "Mountain Peak"),
  loc("Snøballkrig", "Snowball Fight"),
  loc("Termosen", "Thermos Stop"),
  loc("Hengekøya", "Hammock Spot"),
  loc("Påskepynt-verksted", "Easter Decoration Workshop"),
  loc("Lammefjøset", "Lamb Barn"),
  loc("Vedhugging", "Wood Chopping"),
  loc("Fisketur", "Fishing Trip"),
  loc("Morgentrim", "Morning Exercise"),
  loc("Kakaostasjonen", "Hot Cocoa Station"),
];

const WEEKEND_LOCATIONS: LocationCard[] = [
  loc("Rømningsrom", "Escape Room"),
  loc("Karaokebar", "Karaoke Bar"),
  loc("Bowlinghall", "Bowling Alley"),
  loc("Brettspillkafé", "Board Game Cafe"),
  loc("Nattklubb", "Night Club"),
  loc("Konsertarena", "Concert Venue"),
  loc("Takterrasse", "Rooftop Bar"),
  loc("Matmarked", "Street Food Market"),
  loc("Festivalcamp", "Festival Camp"),
  loc("Minigolfbane", "Mini Golf Course"),
  loc("Paintballbane", "Paintball Arena"),
  loc("Drive-in kino", "Drive-in Cinema"),
  loc("Søndagsbrunsj", "Sunday Brunch Spot"),
  loc("Hyttetur", "Cabin Getaway"),
  loc("Badeland", "Water Park"),
  loc("Trampolinepark", "Trampoline Park"),
  loc("Spillhall", "Arcade"),
  loc("Quiz-kveld", "Pub Quiz"),
  loc("Stand-up show", "Comedy Club"),
  loc("Vinbar", "Wine Bar"),
  loc("Tapasrestaurant", "Tapas Restaurant"),
  loc("Sushirestaurant", "Sushi Restaurant"),
  loc("Bryggeripub", "Brewery Pub"),
  loc("Cocktailbar", "Cocktail Bar"),
  loc("Jazzklubb", "Jazz Club"),
  loc("Loppemarknad", "Flea Market"),
  loc("Kunstutstilling", "Art Exhibition"),
  loc("Filmfestival", "Film Festival"),
  loc("Matfestival", "Food Festival"),
  loc("Gatemarked", "Street Market"),
  loc("Klatreparken", "Climbing Park"),
  loc("Lasertag-arena", "Laser Tag Arena"),
  loc("Go-kartbane", "Go-Kart Track"),
  loc("Dart-turnering", "Darts Tournament"),
  loc("Biljardbar", "Pool Hall"),
  loc("Diskotek", "Disco"),
  loc("Spakvelg", "Spa Weekend"),
  loc("Yogaretreat", "Yoga Retreat"),
  loc("Vinslottet", "Wine Castle"),
  loc("Pizzakveld", "Pizza Night"),
];

const SPICY_LOCATIONS: LocationCard[] = [
  loc("VIP-salong", "VIP Lounge"),
  loc("Forhandlingsrom", "Negotiation Room"),
  loc("Kommandosentral", "Command Center"),
  loc("Gjennomgangsrom", "Due Diligence Room"),
  loc("Etterlevelsesrom", "Compliance Review Room"),
  loc("Juryrom", "Jury Deliberation Room"),
  loc("Kriseledelsesrom", "Crisis Management Room"),
  loc("Bakscenen", "Backstage Area"),
  loc("Artistgarderoben", "Green Room"),
  loc("Auksjonshusets bakrom", "Auction Back Office"),
  loc("Diplomatisk mottaksrom", "Diplomatic Reception Room"),
  loc("Lukket styremøte", "Closed Board Meeting"),
  loc("Pokerrom", "Private Poker Room"),
  loc("Sikkerhetsarkiv", "Security Archive"),
  loc("Pressesenter", "Press Operations Center"),
  loc("Datahall", "Data Center Hall"),
  loc("Beredskapsrom", "Observability War Room"),
  loc("Aksjonærsmøte", "Shareholder Meeting"),
  loc("Strategimøte", "Strategy Session"),
  loc("Hemmelig kontor", "Secret Office"),
  loc("Avhørsrom", "Interrogation Room"),
  loc("Kontrolltårn", "Control Tower"),
  loc("Operasjonssal", "Operating Theater"),
  loc("Laboratoriet", "Laboratory"),
  loc("Atom-bunker", "Nuclear Bunker"),
  loc("Overvåkningsrom", "Surveillance Room"),
  loc("Våpenkammer", "Armory"),
  loc("Kasino VIP", "Casino VIP Room"),
  loc("Privat museum", "Private Museum"),
  loc("Hvelvet", "The Vault"),
  loc("Opptaksstudio", "Recording Studio"),
  loc("Filmstudio", "Film Set"),
  loc("Regissørstolen", "Director's Chair"),
  loc("Produksjonskontor", "Production Office"),
  loc("Markedsføringsmøte", "Marketing Meeting"),
  loc("Analyserommet", "Analytics Room"),
  loc("Serverrommet", "Server Room"),
  loc("CEO-kontoret", "CEO Office"),
  loc("Styrerommet", "Boardroom"),
  loc("Klubbhuset", "Private Club"),
];

export const PACKS: LocationPack[] = [
  {
    id: "classic",
    emoji: "🕵️",
    name: { nb: "Klassisk", en: "Classic" },
    locations: CLASSIC_LOCATIONS,
  },
  {
    id: "norway",
    emoji: "🇳🇴",
    name: { nb: "Norge", en: "Norway" },
    locations: NORWAY_LOCATIONS,
  },
  {
    id: "afterski",
    emoji: "🎿",
    name: { nb: "Afterski", en: "Après-Ski" },
    locations: AFTERSKI_LOCATIONS,
  },
  {
    id: "easter",
    emoji: "🐣",
    name: { nb: "Påske", en: "Easter" },
    locations: EASTER_LOCATIONS,
  },
  {
    id: "weekend",
    emoji: "🪩",
    name: { nb: "Helg", en: "Weekend" },
    locations: WEEKEND_LOCATIONS,
  },
  {
    id: "spicy",
    emoji: "🌶️",
    name: { nb: "Ekspert", en: "Expert" },
    locations: SPICY_LOCATIONS,
  },
];
