import type { Locale } from "./types";

export const COPY = {
  nb: {
    brandKicker: "Et sosialt lagspill",
    languageLabel: "Språk",
    themeLabel: "Tema",
    norwegian: "Norsk",
    english: "Engelsk",
    dark: "Mørk",
    light: "Lys",
    players: "Spillere",
    playersIntro: "Les dette før dere starter runden:",
    rulesTitle: "Regler",
    rulePlayerCount: "Vær 3-12 spillere.",
    rulePassPhone: "Send telefonen videre etter hver visning.",
    ruleNoPeeking: "Kun aktiv spiller skal se skjermen.",
    ruleDiscussion: "Still spørsmål uten å avsløre lokasjonen.",
    nameFor: "Navn for",
    remove: "Fjern",
    addPlayer: "+ Legg til spiller",
    setup: "Oppsett",
    spiesCount: "Antall spioner",
    includeRoles: "Bruk roller",
    locationPacks: "Lokasjonspakker",
    scoreboard: "Poengtavle",
    startRound: "Start runde",
    step: "Steg",
    of: "av",
    revealPrompt: "Trykk for å se hemmelig informasjon. Ingen andre skal se skjermen.",
    youAreSpy: "DU ER SPION",
    youAreAgent: "DU ER AGENT",
    spyInstruction: "Spill rolig. Still smarte spørsmål. Prøv å gjette lokasjonen.",
    location: "Lokasjon",
    role: "Rolle",
    showCard: "Vis kort",
    hideAndPass: "Skjul og gi videre",
    discussion: "Diskusjon",
    discussionInstruction: "Alle stiller spørsmål. Finn spionen uten å avsløre lokasjonen.",
    hintLabel: "Hint til neste spørsmål:",
    newHint: "Nytt hint",
    pointAtSuspect: "Pek på mistenkt",
    pointAtSuspectHelp: "Når gruppen er enig, pek ut en spiller direkte.",
    spyGuessAction: "Spion gjetter lokasjon",
    endRound: "Avslutt runde",
    lastChance: "Siste sjanse",
    spyGuessTitle: "Spionens gjetning",
    guessLocation: "Gjett lokasjonen",
    whichSpyGuesses: "Hvilken spion gjetter?",
    guessPlaceholder: "Skriv lokasjonen...",
    submitGuess: "Send gjetning",
    backToDiscussion: "Tilbake til diskusjon",
    result: "Resultat",
    spiesWon: "Spionene vant",
    agentsWon: "Agentene vant",
    newRound: "Ny runde",
    toSetup: "Til oppsett",
    spyShort: "Spion",
    roleShort: "Rolle",
    reasons: {
      timeout: "Tiden gikk ut. Spionene overlevde runden.",
      wrongVote: (name: string) => `${name} ble pekt ut, men var ikke spion.`,
      spyGuessCorrect: "Spionen gjettet lokasjonen riktig.",
      caughtSpyWrongGuess: "Spionen ble tatt og gjettet feil.",
      freeSpyWrongGuess: "Spionen gjettet feil lokasjon.",
      manualEnd: "Runden ble avsluttet manuelt.",
    },
  },
  en: {
    brandKicker: "Social deduction game",
    languageLabel: "Language",
    themeLabel: "Theme",
    norwegian: "Norwegian",
    english: "English",
    dark: "Dark",
    light: "Light",
    players: "Players",
    playersIntro: "Read this before starting:",
    rulesTitle: "Rules",
    rulePlayerCount: "Be 3-12 players.",
    rulePassPhone: "Pass the phone after each reveal.",
    ruleNoPeeking: "Only the active player should see the screen.",
    ruleDiscussion: "Ask questions without exposing the location.",
    nameFor: "Name for",
    remove: "Remove",
    addPlayer: "+ Add player",
    setup: "Setup",
    spiesCount: "Number of spies",
    includeRoles: "Use roles",
    locationPacks: "Location packs",
    scoreboard: "Scoreboard",
    startRound: "Start round",
    step: "Step",
    of: "of",
    revealPrompt: "Tap to see your secret information. No one else should look.",
    youAreSpy: "YOU ARE THE SPY",
    youAreAgent: "YOU ARE AN AGENT",
    spyInstruction: "Stay calm. Ask smart questions. Try to guess the location.",
    location: "Location",
    role: "Role",
    showCard: "Show card",
    hideAndPass: "Hide and pass",
    discussion: "Discussion",
    discussionInstruction: "Ask questions. Find the spy without exposing the location.",
    hintLabel: "Hint for the next question:",
    newHint: "New hint",
    pointAtSuspect: "Point at suspect",
    pointAtSuspectHelp: "When your group agrees, point directly at one player.",
    spyGuessAction: "Spy guesses location",
    endRound: "End round",
    lastChance: "Last chance",
    spyGuessTitle: "Spy guess",
    guessLocation: "Guess the location",
    whichSpyGuesses: "Which spy is guessing?",
    guessPlaceholder: "Type the location...",
    submitGuess: "Submit guess",
    backToDiscussion: "Back to discussion",
    result: "Result",
    spiesWon: "Spies won",
    agentsWon: "Agents won",
    newRound: "New round",
    toSetup: "Back to setup",
    spyShort: "Spy",
    roleShort: "Role",
    reasons: {
      timeout: "Time ran out. The spies survived the round.",
      wrongVote: (name: string) => `${name} was pointed out, but was not a spy.`,
      spyGuessCorrect: "The spy guessed the location correctly.",
      caughtSpyWrongGuess: "The caught spy guessed wrong.",
      freeSpyWrongGuess: "The spy guessed the wrong location.",
      manualEnd: "The round was ended manually.",
    },
  },
} as const;

export type AppText = (typeof COPY)[Locale];
