import type { Locale } from "./types";

export const COPY = {
  nb: {
    brandKicker: "Et sosialt lagspill",
    languageLabel: "Språk",
    themeLabel: "Tema",
    norwegian: "Norsk",
    english: "Engelsk",
    dark: "Mørk",
    light: "Lys",
    players: "Spillere",
    playersIntro: "Les dette før dere starter runden:",
    rulesTitle: "Regler",
    rulePlayerCount: "Vær 3-12 spillere.",
    rulePassPhone: "Send telefonen videre etter hver visning.",
    ruleNoPeeking: "Kun aktiv spiller skal se skjermen.",
    ruleDiscussion: "Send telefonen én runde til og stem på hvem du tror er spion.",
    nameFor: "Navn for",
    remove: "Fjern",
    addPlayer: "+ Legg til spiller",
    setup: "Oppsett",
    spiesCount: "Antall spioner",
    includeRoles: "Bruk roller",
    locationPacks: "Lokasjonspakker",
    startRound: "Start runde",
    step: "Steg",
    of: "av",
    revealPrompt: "Trykk for å se hemmelig informasjon. Ingen andre skal se skjermen.",
    youAreSpy: "DU ER SPION",
    youAreAgent: "DU ER AGENT",
    spyInstruction: "Spill rolig. Still smarte spørsmål. Prøv å gjette lokasjonen.",
    location: "Lokasjon",
    role: "Rolle",
    showCard: "Vis kort",
    hideAndPass: "Skjul og gi videre",
    voting: "Avstemning",
    votingInstruction: "Telefonen sendes én runde. Hver spiller velger hvem de tror er spion.",
    votingTurn: "Stemmer nå",
    votingQuestion: "Hvem tror du er spion?",
    voteFor: "Stem på",
    lastChance: "Siste sjanse",
    spyGuessTitle: "Spionens gjetning",
    guessLocation: "Gjett lokasjonen",
    whichSpyGuesses: "Hvilken spion gjetter?",
    guessPlaceholder: "Skriv lokasjonen...",
    submitGuess: "Send gjetning",
    result: "Resultat",
    spiesWon: "Spionene vant",
    agentsWon: "Agentene vant",
    newRound: "Ny runde",
    toSetup: "Til oppsett",
    spyShort: "Spion",
    roleShort: "Rolle",
    reasons: {
      wrongVote: (name: string) => `${name} fikk flest stemmer, men var ikke spion.`,
      voteTie: "Det ble stemmelikhet. Spionene slipper unna.",
      spyGuessCorrect: "Spionen gjettet lokasjonen riktig.",
      caughtSpyWrongGuess: "Spionen ble tatt og gjettet feil.",
    },
  },
  en: {
    brandKicker: "Social deduction game",
    languageLabel: "Language",
    themeLabel: "Theme",
    norwegian: "Norwegian",
    english: "English",
    dark: "Dark",
    light: "Light",
    players: "Players",
    playersIntro: "Read this before starting:",
    rulesTitle: "Rules",
    rulePlayerCount: "Be 3-12 players.",
    rulePassPhone: "Pass the phone after each reveal.",
    ruleNoPeeking: "Only the active player should see the screen.",
    ruleDiscussion: "Pass the phone one more round and vote for who you think is the spy.",
    nameFor: "Name for",
    remove: "Remove",
    addPlayer: "+ Add player",
    setup: "Setup",
    spiesCount: "Number of spies",
    includeRoles: "Use roles",
    locationPacks: "Location packs",
    startRound: "Start round",
    step: "Step",
    of: "of",
    revealPrompt: "Tap to see your secret information. No one else should look.",
    youAreSpy: "YOU ARE THE SPY",
    youAreAgent: "YOU ARE AN AGENT",
    spyInstruction: "Stay calm. Ask smart questions. Try to guess the location.",
    location: "Location",
    role: "Role",
    showCard: "Show card",
    hideAndPass: "Hide and pass",
    voting: "Voting",
    votingInstruction: "Pass the phone one round. Each player votes for who they think is the spy.",
    votingTurn: "Now voting",
    votingQuestion: "Who do you think is the spy?",
    voteFor: "Vote for",
    lastChance: "Last chance",
    spyGuessTitle: "Spy guess",
    guessLocation: "Guess the location",
    whichSpyGuesses: "Which spy is guessing?",
    guessPlaceholder: "Type the location...",
    submitGuess: "Submit guess",
    result: "Result",
    spiesWon: "Spies won",
    agentsWon: "Agents won",
    newRound: "New round",
    toSetup: "Back to setup",
    spyShort: "Spy",
    roleShort: "Role",
    reasons: {
      wrongVote: (name: string) => `${name} got the most votes, but was not a spy.`,
      voteTie: "The vote ended in a tie. The spies got away.",
      spyGuessCorrect: "The spy guessed the location correctly.",
      caughtSpyWrongGuess: "The caught spy guessed wrong.",
    },
  },
} as const;

export type AppText = (typeof COPY)[Locale];
