import type { Locale } from "./types";

export const COPY = {
  nb: {
    brandKicker: "Finn spionen",
    languageLabel: "Språk",
    themeLabel: "Tema",
    norwegian: "Norsk",
    english: "Engelsk",
    dark: "Mørk",
    light: "Lys",
    players: "Spillere",
    playersIntro: "Les dette før dere starter runden:",
    rulesTitle: "Regler",
    rulePlayerCount: "Vær 3-12 spillere.",
    rulePassPhone: "Send telefonen videre etter hver visning.",
    ruleNoPeeking: "Kun aktiv spiller skal se skjermen.",
    ruleDiscussion: "Send telefonen én runde til og stem på hvem du tror er spion.",
    nameFor: "Navn for",
    remove: "Fjern",
    addPlayer: "+ Legg til spiller",
    spiesCount: "Antall spioner",
    pointVoting: "Pek ut spionen",
    manualVotingHint: "Alle sier ordet sitt høyt før dere peker utenfor appen.",
    decreaseSpyCount: "Reduser antall spioner",
    increaseSpyCount: "Øk antall spioner",
    locationPacks: "Lokasjonspakker",
    startRound: "Start runde",
    step: "Steg",
    of: "av",
    revealPrompt: "Trykk for å se hemmelig informasjon. Ingen andre skal se skjermen.",
    youAreSpy: "DU ER SPION",
    youAreAgent: "DU ER AGENT",
    spyInstruction: "Spill rolig. Still smarte spørsmål. Prøv å gjette lokasjonen.",
    location: "Lokasjon",
    showCard: "Vis kort",
    hideAndPass: "Skjul og gi videre",
    voting: "Avstemning",
    votingInstruction: "Telefonen sendes én runde. Hver spiller velger hvem de tror er spion.",
    votingTurn: "Stemmer nå",
    votingQuestion: "Hvem tror du er spion?",
    voteFor: "Stem på",
    manualVoteTitle: "Pek ut spionen",
    manualVoteInstruction: "Alle sier ordet sitt høyt. Deretter peker alle samtidig på den de tror er spion.",
    showResult: "Vis resultat",
    result: "Resultat",
    spyWon: "Spionen vant",
    spiesWon: "Spionene vant",
    agentsWon: "Agentene vant",
    manualRound: "Runden er ferdig",
    newRound: "Ny runde",
    toSetup: "Til oppsett",
    spyShort: "Spion",
    agentShort: "Agent",
    reasons: {
      wrongVote: (name: string) => `${name} fikk flest stemmer, men var ikke spion.`,
      voteTie: "Det ble stemmelikhet. Spionene slipper unna.",
      caughtSpy: "Spionen ble avslørt i avstemningen.",
      manualVoting: "Stemming ble gjort ved peking utenfor appen.",
    },
  },
  en: {
    brandKicker: "Find the spy",
    languageLabel: "Language",
    themeLabel: "Theme",
    norwegian: "Norwegian",
    english: "English",
    dark: "Dark",
    light: "Light",
    players: "Players",
    playersIntro: "Read this before starting:",
    rulesTitle: "Rules",
    rulePlayerCount: "Be 3-12 players.",
    rulePassPhone: "Pass the phone after each reveal.",
    ruleNoPeeking: "Only the active player should see the screen.",
    ruleDiscussion: "Pass the phone one more round and vote for who you think is the spy.",
    nameFor: "Name for",
    remove: "Remove",
    addPlayer: "+ Add player",
    spiesCount: "Number of spies",
    pointVoting: "Point out the spy",
    manualVotingHint: "Everyone says their word out loud before pointing outside the app.",
    decreaseSpyCount: "Decrease number of spies",
    increaseSpyCount: "Increase number of spies",
    locationPacks: "Location packs",
    startRound: "Start round",
    step: "Step",
    of: "of",
    revealPrompt: "Tap to see your secret information. No one else should look.",
    youAreSpy: "YOU ARE THE SPY",
    youAreAgent: "YOU ARE AN AGENT",
    spyInstruction: "Stay calm. Ask smart questions. Try to guess the location.",
    location: "Location",
    showCard: "Show card",
    hideAndPass: "Hide and pass",
    voting: "Voting",
    votingInstruction: "Pass the phone one round. Each player votes for who they think is the spy.",
    votingTurn: "Now voting",
    votingQuestion: "Who do you think is the spy?",
    voteFor: "Vote for",
    manualVoteTitle: "Point out the spy",
    manualVoteInstruction: "Everyone says their word out loud. Then everyone points at the person they think is the spy.",
    showResult: "Show result",
    result: "Result",
    spyWon: "Spy won",
    spiesWon: "Spies won",
    agentsWon: "Agents won",
    manualRound: "Round complete",
    newRound: "New round",
    toSetup: "Back to setup",
    spyShort: "Spy",
    agentShort: "Agent",
    reasons: {
      wrongVote: (name: string) => `${name} got the most votes, but was not a spy.`,
      voteTie: "The vote ended in a tie. The spies got away.",
      caughtSpy: "The spy was identified in the vote.",
      manualVoting: "Voting was done by pointing outside the app.",
    },
  },
} as const;

export type AppText = (typeof COPY)[Locale];
